name: course
channels:
  - conda-forge
  - defaults
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - arrow-cpp=21.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - datasets=3.3.2
  - dill=0.3.8
  - expat=2.7.1
  - faiss=1.9.0
  - faiss-cpu=1.9.0
  - filelock=3.17.0
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.5.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.15.0
  - libcxx=20.1.8
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.71.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libuv=1.48.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy-base=1.26.4
  - openssl=3.5.4
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.2
  - propcache=0.3.1
  - protobuf=5.29.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.3
  - requests=2.32.5
  - safetensors=0.5.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tokenizers=0.21.0
  - tqdm=4.67.1
  - transformers=4.51.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - utf8proc=2.6.1
  - uvloop=0.21.0
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - annotated-types==0.7.0
    - anyio==4.11.0
    - backoff==2.2.1
    - bcrypt==5.0.0
    - build==1.3.0
    - cachetools==6.2.1
    - chromadb==1.1.1
    - click==8.3.0
    - coloredlogs==15.0.1
    - dataclasses-json==0.6.7
    - distro==1.9.0
    - durationpy==0.10
    - exceptiongroup==1.3.0
    - flatbuffers==25.9.23
    - google-auth==2.41.1
    - googleapis-common-protos==1.70.0
    - grpcio==1.75.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httptools==0.7.1
    - httpx==0.28.1
    - httpx-sse==0.4.3
    - humanfriendly==10.0
    - idna==3.10
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - jiter==0.11.0
    - joblib==1.5.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kubernetes==34.1.0
    - langchain==1.0.0a14
    - langchain-community==0.3.31
    - langchain-core==1.0.0a8
    - langchain-openai==1.0.0a4
    - langchain-text-splitters==0.3.11
    - langgraph==1.0.0a4
    - langgraph-checkpoint==2.1.2
    - langgraph-prebuilt==0.7.0a2
    - langgraph-sdk==0.2.9
    - langsmith==0.4.35rc1
    - markdown-it-py==4.0.0
    - marshmallow==3.26.1
    - mdurl==0.1.2
    - mmh3==5.2.0
    - mpmath==1.3.0
    - mypy-extensions==1.1.0
    - nltk==3.9.2
    - numpy==2.2.6
    - oauthlib==3.3.1
    - onnxruntime==1.23.1
    - openai==2.3.0
    - opentelemetry-api==1.37.0
    - opentelemetry-exporter-otlp-proto-common==1.37.0
    - opentelemetry-exporter-otlp-proto-grpc==1.37.0
    - opentelemetry-proto==1.37.0
    - opentelemetry-sdk==1.37.0
    - opentelemetry-semantic-conventions==0.58b0
    - orjson==3.11.3
    - ormsgpack==1.11.0
    - overrides==7.7.0
    - pillow==11.3.0
    - posthog==5.4.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pybase64==1.4.2
    - pydantic==2.12.0
    - pydantic-core==2.41.1
    - pydantic-settings==2.11.0
    - pygments==2.19.2
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - python-dotenv==1.1.1
    - referencing==0.37.0
    - regex==2025.9.18
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==14.2.0
    - rpds-py==0.27.1
    - rsa==4.9.1
    - shellingham==1.5.4
    - sniffio==1.3.1
    - sqlalchemy==2.0.44
    - sympy==1.14.0
    - tenacity==9.1.2
    - tiktoken==0.12.0
    - tomli==2.3.0
    - typer==0.19.2
    - typing-inspect==0.9.0
    - typing-inspection==0.4.2
    - urllib3==2.3.0
    - uvicorn==0.37.0
    - watchfiles==1.1.0
    - websocket-client==1.9.0
    - websockets==15.0.1
    - zipp==3.23.0
    - zstandard==0.25.0